# config.yaml

general:
  script_name: "add_abstract_embeddings.py"
  description: "This script creates embeddings for abstracts."
  version: "1.0.0"

database:
  uri: 'bolt://localhost:7687'
  username: 'neo4j'
  password: 'neo4j_is_the_best'
  database: 'neo4j'

model:
  model_id: "meta-llama/Llama-3.2-1B"
