# config.yaml

general:
  script_name: "add_papers_from_title_list.py"
  description: "This script creates a set of paper nodes and possibly author nodes."
  version: "1.0.0"
  verbose: False

database:
  uri: 'bolt://localhost:7687'
  username: 'neo4j'
  password: 'neo4j_is_the_best'
  database: 'new'

file_paths:
  paper_titles: "C:/Users/tjker/Desktop/Research/Projects/lit_review/data/paper_titles.txt"
  output: "/path/to/output"

api:
  max_retries: 10
  base_delay: 1
  max_delay: 512

graph:
  author: True
  citation: True
  citation_fields: ["title", "abstract", "citationCount", "publicationDate", "authors"]